### PR TITLE
Add exports field

### PR DESCRIPTION
**Pull request by perrin4869**
This fixes `import dotenv-flow/config` from inside an `mjs` module

### CODE REVIEW

**Comment by kerimdzhanov** [comment]
Hi @perrin4869,

Thanks a lot for the PR! That makes total sense.

The only question I am thinking about is how can we make sure that it won't break existing Node.js's `require()` behavior in different versions/transpilers/environments? And maybe for the future as well, when we will be making some related changes to `package.json`, how can we make sure that we won't break this new TS/ES6's `import` behavior?

I am thinking of some kind of CI test for it 🤔, any ideas?

**Comment by perrin4869** [comment]
I added some tests here! Not very thorough though 😅

**Review by kerimdzhanov — APPROVED** [review]
Nicely done! Thanks a lot 🤗

**Comment by kerimdzhanov** [comment]
Hi @perrin4869, could you please rebase? Feel free to rewrite with your own version of `yarn.lock`, I am going to update all the dependencies in a separate commit.

**Comment by kerimdzhanov** [comment]
All good, no worries. I've figured out how can I rebase myself 😅

✅ Merged as commit 352888b.

Thanks a lot for the PR!

**Pull request closed without merging**
