### PR TITLE
feat(dotenv): add support for dotenv-expand

### LINKED ISSUE #9: Consider adding support for dotenv-expand
[`dotenv-expand`](https://github.com/motdotla/dotenv-expand) allows developers to reference process.env variables inside their `.env` files.

For example:

```
IP=127.0.0.1
PORT=1234
APP_URL=http://${IP}:${PORT}
```

Using the above example `.env` file, `process.env.APP_URL` would be `http://127.0.0.1:1234`.

### PR DESCRIPTION
**Pull request by ericrallen**
Just in case you're interested in adding support for `dotenv-expand` here's a PR that does it.

Closes #9 

Feel free to close it if you don't want to add `dotenv-expand` support.

### CODE REVIEW

**Comment by kerimdzhanov** [comment]
Thank you!

**Comment by kerimdzhanov** [comment]
Sorry, I've made a hasty decision.

I've reverted this PR in favor of creating a separate library for this feature (like `dotenv-flow-expand`).
It should be done in the same way as `dotenv-expand` does for `dotenv`.

**Comment by ericrallen** [comment]
I'm not entirely sure how you plan to handle it, but if you need any help implementing `dotenv-expand` don't hesitate to reach out.

**Comment by kerimdzhanov** [comment]
I've reviewed the source code of `dotenv-expand` and I think it already works, we even don't need any intermediate library.

`dotenv-flow`'s `.config()` method returns the same object (or `error`) as the `dotenv`'s. So the following should work as well:

```js
const dotenvFlow = require('dotenv-flow');
const dotenvExpand = require('dotenv-expand');

const myEnv = dotenv.config();
dotenvExpand(myEnv);
```

It is the same as in `dotenv-expand`'s `README.md`, but with `dotenv-flow` instead of `dotenv`.

Please, let me know if I missed something.

**Comment by ericrallen** [comment]
@kerimdzhanov Yeah, that's what this PR introduced (along with some tests to verify that it was working as intended).

I wasn't sure if I was missing something about how you planned to implement it as a secondary package, because this seemed like the most logical way to implement it, but it's your package so I didn't want to make assumptions.

**Comment by kerimdzhanov** [comment]
If I understand correctly, we don't need to make any changes and don't need a secondary package to make it work. Maybe just update the `README.md` file adding the section about how to use `dotenv-expand` with `dotenv-flow` with the example above. Isn't it?

**Comment by kerimdzhanov** [comment]
Nice! Thanks for your participation! 👍

**Pull request merged**
